# Logger module
CONFIG_LOG=y


# Formatowanie float w logach
CONFIG_CBPRINTF_FP_SUPPORT=y

# BLE
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="Node Friend"
CONFIG_BT_OBSERVER=y
CONFIG_BT_BROADCASTER=y

# BLE Mesh
CONFIG_BT_MESH=y

# Provisioning na sztywno
CONFIG_BT_MESH_PB_ADV=y

# Config Client
CONFIG_BT_MESH_CFG_CLI=y
CONFIG_BT_MESH_HEALTH_CLI=y

# Sensor Client
CONFIG_BT_MESH_SENSOR_CLI=y

# Friend
CONFIG_BT_MESH_FRIEND=y
CONFIG_BT_MESH_FRIEND_LPN_COUNT=2

# Limity sieci
CONFIG_BT_MESH_SUBNET_COUNT=1
CONFIG_BT_MESH_APP_KEY_COUNT=1
CONFIG_BT_MESH_MODEL_GROUP_COUNT=2

# Trwalosc wylaczona (nie zapisujemy do flasha)
CONFIG_BT_SETTINGS=n

# Tuning stosow i buforow
CONFIG_MAIN_STACK_SIZE=4400
CONFIG_MAIN_THREAD_PRIORITY=-2
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4800
CONFIG_BT_MESH_ADV_STACK_SIZE=4000
CONFIG_BT_RX_STACK_SIZE=3300
CONFIG_BT_MESH_ADV_BUF_COUNT=10

# Segmentacja
CONFIG_BT_MESH_RX_SEG_MAX=32
CONFIG_BT_MESH_TX_SEG_MSG_COUNT=3
