manifest:
  version: "1.2"

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect


  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v3.4.0
      import:
        path-prefix: deps

  self:
    path: app
